### ISSUE TITLE
Npm run serve  Failed

### ISSUE THREAD

**Issue by Yourdigitalheart** [codingfriend1/Feathers-Vue#1]
Hello I can't start OSX npm -v
3.10.10
Thanks
```
Cannot read property 'type' of undefined
[Vue warn]: Error in beforeCreate hook:
(found in <SimpleInput>)
Error rendering to string:
TypeError: Cannot read property 'type' of undefined
    at VueComponent.proxyGetter [as type] (__vue_ssr_bundle__:10857:28)
    at VueComponent.beforeCreate (__vue_ssr_bundle__:76226:22)
    at callHook (__vue_ssr_bundle__:10483:22)
    at VueComponent.Vue._init (__vue_ssr_bundle__:11923:6)
    at new VueComponent (__vue_ssr_bundle__:12091:13)
    at createComponentInstanceForVnode (/Users/insidebox/Desktop/insidebox-v2/node_modules/vue-server-renderer/build.js:5143:10)
    at renderComponent (/Users/insidebox/Desktop/insidebox-v2/node_modules/vue-server-renderer/build.js:6637:40)
    at RenderContext.renderNode (/Users/insidebox/Desktop/insidebox-v2/node_modules/vue-server-renderer/build.js:6622:7)
    at RenderContext.next (/Users/insidebox/Desktop/insidebox-v2/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/Users/insidebox/Desktop/insidebox-v2/node_modules/vue-server-renderer/build.js:30:9)
Cannot read property 'type' of undefined
```

**Comment by codingfriend1** [comment]
This repo requires node version 7.4 or higher. Also did you run `npm run watch` in one terminal, mongod in a second, and `npm run serve` on the third? And do a yarn install?

**Comment by rbajaniya** [comment]
I getting some issue.
I follow below instruction but some issue found.
Please help me

**Comment by codingfriend1** [comment]
Which branch are you running? Which version of node are you using? What does the error say?

**Comment by codingfriend1** [comment]
Are you continuing to have problems with this?

**Comment by Yourdigitalheart** [comment]
I don't know I stop to use it 
Thanks
